#include <stdio.h>
#include <string.h>
#include <sys/param.h>
#include "example_common.h"

#define BOOTLOADER_ADDRESS_V1 0x0
#define PARTITION_ADDRESS     0x8000
#define APPLICATION_ADDRESS   0x10000

// Symbols generated by bin2array from target_binaries/ESP32_C6
extern const uint8_t  ESP32_C6_bootloader_bin[];
extern const uint32_t ESP32_C6_bootloader_bin_size;
extern const uint8_t  ESP32_C6_bootloader_bin_md5[];
extern const uint8_t  ESP32_C6_c6_messenger_bin[];
extern const uint32_t ESP32_C6_c6_messenger_bin_size;
extern const uint8_t  ESP32_C6_c6_messenger_bin_md5[];
extern const uint8_t  ESP32_C6_partition_table_bin[];
extern const uint32_t ESP32_C6_partition_table_bin_size;
extern const uint8_t  ESP32_C6_partition_table_bin_md5[];

static const char *get_error_string(const esp_loader_error_t error)
{
    const char *mapping[ESP_LOADER_ERROR_INVALID_RESPONSE + 1] = {
        "NONE", "UNKNOWN", "TIMEOUT", "IMAGE SIZE",
        "INVALID MD5", "INVALID PARAMETER", "INVALID TARGET",
        "UNSUPPORTED CHIP", "UNSUPPORTED FUNCTION", "INVALID RESPONSE"
    };
    return mapping[error <= ESP_LOADER_ERROR_INVALID_RESPONSE ? error : 0];
}

void get_example_binaries(target_chip_t target, example_binaries_t *bins)
{
    (void)target; // Only ESP32-C6 used in this project
    bins->boot.data = ESP32_C6_bootloader_bin;
    bins->boot.size = ESP32_C6_bootloader_bin_size;
    bins->boot.md5  = ESP32_C6_bootloader_bin_md5;
    bins->boot.addr = BOOTLOADER_ADDRESS_V1;

    bins->part.data = ESP32_C6_partition_table_bin;
    bins->part.size = ESP32_C6_partition_table_bin_size;
    bins->part.md5  = ESP32_C6_partition_table_bin_md5;
    bins->part.addr = PARTITION_ADDRESS;

    bins->app.data  = ESP32_C6_c6_messenger_bin;
    bins->app.size  = ESP32_C6_c6_messenger_bin_size;
    bins->app.md5   = ESP32_C6_c6_messenger_bin_md5;
    bins->app.addr  = APPLICATION_ADDRESS;
}

esp_loader_error_t connect_to_target(uint32_t higher_transmission_rate)
{
    esp_loader_connect_args_t connect_config = ESP_LOADER_CONNECT_DEFAULT();
    esp_loader_error_t err = esp_loader_connect(&connect_config);
    if (err != ESP_LOADER_SUCCESS) {
        printf("Cannot connect to target. Error: %s\n", get_error_string(err));
        return err;
    }
    printf("Connected to target\n");
    (void)higher_transmission_rate; // not used for SDIO
    return ESP_LOADER_SUCCESS;
}

esp_loader_error_t flash_binary(const uint8_t *bin, size_t size, size_t address)
{
    esp_loader_error_t err;
    static uint8_t payload[1024];
    const uint8_t *bin_addr = bin;

    printf("Erasing flash (this may take a while)...\n");
    err = esp_loader_flash_start(address, size, sizeof(payload));
    if (err != ESP_LOADER_SUCCESS) {
        printf("Erasing flash failed with error: %d\n", err);
        return err;
    }
    printf("Start programming\n");

    size_t binary_size = size;
    size_t written = 0;

    while (size > 0) {
        size_t to_read = MIN(size, sizeof(payload));
        memcpy(payload, bin_addr, to_read);

        err = esp_loader_flash_write(payload, to_read);
        if (err != ESP_LOADER_SUCCESS) {
            printf("\nPacket could not be written! Error %d.\n", err);
            return err;
        }

        size -= to_read;
        bin_addr += to_read;
        written += to_read;

        int progress = (int)(((float)written / binary_size) * 100);
        printf("\rProgress: %d %%", progress);
    };

    printf("\nFinished programming\n");
    return ESP_LOADER_SUCCESS;
}

